development:
  adapter: postgresql
  database: mydb
  username: troys
  password: slayer
  host: localhost

production:
  adapter: postgresql
  host: hmmmm
  username: user
  database: mydb-production
